stages:
  - install
  - build
  - release

# Caching dependencies
cache:
  paths:
    - node_modules/
    - android/.gradle
    - android/build/

# Install dependencies
install_dependencies:
  stage: install
  image: reactnativecommunity/react-native-android:latest  # Use the pre-configured image
  script:
    - npm install -g react-native-cli  # Install React Native CLI globally
    - npm install  # Install project dependencies
  only:
    - main

# Build AAB
build_aab:
  stage: build
  image: reactnativecommunity/react-native-android:latest  # Use the pre-configured image
  before_script:
    - echo "$KEYSTORE_FILE" | base64 -d > android/app/my-upload-key.keystore  # Decode keystore file securely from GitLab CI/CD variables
    - chmod +x android/gradlew  # Add execute permissions to gradlew
    - gem install fastlane  # Install Fastlane
  script:
    - cd android
    - fastlane build_aab  # Use Fastlane to build the AAB
  artifacts:
    paths:
      - android/app/build/outputs/bundle/release/app-release.aab
    expire_in: 1 hour
  only:
    - main


deploy_to_play_store:
  stage: release
  image: ruby:latest
  dependencies:
    - build_aab
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/bundle
  before_script:
    - gem install bundler
    - bundle config set path 'vendor/bundle'
    - bundle install
  script:
    - bundle exec fastlane deploy
  when: manual
  only:
    - main

# Create a GitLab release
create_release:
  stage: release
  script:
    - echo "Creating GitLab release"
  release:
    name: "Release $CI_COMMIT_TAG"
    tag_name: $CI_COMMIT_TAG
    description: "Release of version $CI_COMMIT_TAG"
  when: manual
  only:
    - tags