version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "16.2.0"  # Specify the Xcode version

jobs:
  install_ios_dependencies:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            brew install node
            npm install -g npm
      - run:
          name: Install Project Dependencies
          command: npm install --force
      - run:
          name: Install React Native CLI
          command: npm install -g react-native-cli
      - run:
          name: Install CocoaPods
          command: sudo gem install cocoapods
      - run:
          name: Install CocoaPods Dependencies
          command: |
            cd ios
            pod install
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-modules-{{ checksum "package-lock.json" }}
            - v1-node-modules-
      - restore_cache:
          name: Restore Pods cache
          keys:
            - v1-pods-{{ checksum "ios/Podfile.lock" }}
            - v1-pods-
      - run:
          name: List Directory Contents
          command: |
            cd ios
            ls -la
      - run:
          name: Verify TMS.xcworkspace
          command: |
            cd ios
            if [ ! -d TMS.xcworkspace ]; then
              echo "TMS.xcworkspace does not exist"
              exit 1
            fi
      - save_cache:
          name: Save node_modules cache
          paths:
            - ./node_modules
          key: v1-node-modules-{{ checksum "package-lock.json" }}
      - save_cache:
          name: Save Pods cache
          paths:
            - ./ios/Pods
            - ./ios/Podfile.lock
          key: v1-pods-{{ checksum "ios/Podfile.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - ios/TMS.xcworkspace
            - ios/Pods
            - ios/Podfile.lock

  build_ios:
    executor: macos-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-modules-{{ checksum "package-lock.json" }}
            - v1-node-modules-
      - restore_cache:
          name: Restore Pods cache
          keys:
            - v1-pods-{{ checksum "ios/Podfile.lock" }}
            - v1-pods-
      - run:
          name: List Directory Contents Before Build
          command: |
            cd ios
            ls -la
      - run:
          name: Build iOS App
          command: |
            cd ios
            xcodebuild -workspace TMS.xcworkspace -scheme TMS -sdk iphoneos -configuration Release archive -archivePath $CIRCLE_WORKING_DIRECTORY/build/TMS.xcarchive DEVELOPMENT_TEAM=<Your_Development_Team_ID>
            xcodebuild -exportArchive -archivePath $CIRCLE_WORKING_DIRECTORY/build/TMS.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CIRCLE_WORKING_DIRECTORY/build
      - store_artifacts:
          path: build/TMS.ipa
          destination: build

  deploy_to_app_store:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Install Fastlane
          command: gem install fastlane
      - run:
          name: Upload to Apple App Store
          command: fastlane deliver --ipa build/TMS.ipa --username $APP_STORE_CONNECT_USERNAME --app_identifier $APP_IDENTIFIER --skip_metadata --skip_screenshots --force

workflows:
  version: 2
  build_and_release:
    jobs:
      - install_ios_dependencies
      - build_ios:
          requires:
            - install_ios_dependencies
      - deploy_to_app_store:
          requires:
            - build_ios
          filters:
            branches:
              only:
                - ios_cicd